name    'netmanagers-ssmtp'
version '1.0.4'
author  'Javier Bertoli'
license 'Apache2'
project_page 'http://www.netmanagers.com.ar'
source  'https://github.com/netmanagers/puppet-ssmtp'
summary 'Puppet module for ssmtp'
description 'This module installs and manages ssmtp. Check README for details.'
dependency 'example42/puppi', '>= 2.0.0'
dependency 'puppetlabs/stdlib', '>=4.1.0'
dependency 'puppetlabs/concat', '>=1.0.0'
